version: '3.8'

services:
  alfred:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET=${SECRET:-your-secret-key-here}
      - DEBUG=${DEBUG:-false}
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 